# DontLag 插件配置文件

# 插件設定
settings:
  # 是否在生物 AI 被禁用時在其上方顯示標記
  show-ai-disabled-indicator: true
  
  # 伺服器重啟後是否保留 AI 禁用狀態
  persist-ai-state: false

# 自動村民優化設定
auto-optimize:
  # 是否啟用自動村民優化
  enabled: true
  
  # 村民數量閾值（當某個區塊的村民超過此數量時自動優化）
  threshold: 5
  
  # 檢查間隔（秒）- 建議 30-60 秒
  check-interval: 30
  
  # 說明：
  # - 自動優化是基於區塊（Chunk）的，一個區塊是 16x16 方塊
  # - 當某個區塊的村民數量超過閾值時，該區塊所有村民會被永久優化
  # - 優化後的村民只保留交易和補貨功能，不會再自動恢復
  # - 這有助於大型村民交易所減輕伺服器負擔

# 訊息設定
messages:
  prefix: "&6[DontLag]&r "
  ai-disabled: "&a已關閉 {entity} 的 AI"
  ai-enabled: "&e已恢復 {entity} 的 AI"
  no-permission: "&c你沒有權限使用此功能！"
  tool-enabled: "&a已啟用 AI 控制工具模式！"
  tool-disabled: "&e已關閉 AI 控制工具模式"


