# DontLag 插件配置文件

# 插件設定
settings:
  # 是否在生物 AI 被禁用時在其上方顯示標記
  show-ai-disabled-indicator: true
  
  # 伺服器重啟後是否保留 AI 禁用狀態
  persist-ai-state: false

# 自動村民優化設定
auto-optimize:
  # 是否啟用自動村民優化
  enabled: true
  
  # 村民數量閾值（當某個區塊的村民超過此數量時自動優化）
  threshold: 5
  
  # 檢查間隔（秒）- 建議 30-60 秒
  check-interval: 30
  
  # 密集檢測閾值（0.5格內超過此數量的村民會被強制鎖定）
  # 用於檢測玩家是否濫用繁殖機或使用外掛堆疊村民
  # 強制鎖定的村民需要管理員使用 OP 管理員棒才能解除
  density-threshold: 5
  
  # 智能寬限期系統（固定參數，在代碼中設置）：
  # - 嬰兒村民：完全不會被優化
  # - 成年村民：出生/長大後 30 秒才會開始優化（讓村民有時間移動到暫存區）
  # - 玩家互動：右鍵村民會自動解除優化，並給予 10 分鐘寬限期
  # - 寬限期後：如果 10 分鐘內沒有再次互動，村民會重新被優化
  # - 優化後功能：村民仍可交易、補貨、升級，但不會移動和尋路
  
  # 說明：
  # - 自動優化是基於區塊（Chunk）的，一個區塊是 16x16 方塊
  # - 當某個區塊的村民數量超過閾值時，該區塊符合條件的村民會被永久優化
  # - 繁殖機新生的村民會在成年 30 秒後被優化（不影響初期移動）
  # - 需要使用的村民只要右鍵一下就會自動解除優化，可以移動和領職業
  # - 優化後的村民只保留交易、補貨、升級功能，減輕伺服器負擔
  # - 管理員可使用 /delag op set 獲得 OP 管理員棒來手動解除永久優化

# TPS 監控設定
tps-monitor:
  # 是否啟用 TPS 監控自動停止機制
  enabled: true
  
  # TPS 閾值（當平均 TPS 低於此值時停止村民計算）
  threshold: 15.0
  
  # 說明：
  # - 當伺服器 TPS 過低時，插件會自動停止村民優化計算
  # - 系統會廣播訊息到所有玩家
  # - 管理員可使用 /delag reload 重新啟動
  # - 建議閾值：15.0 TPS（可根據伺服器性能調整）

# Discord 通知設定
discord:
  # Discord Webhook URL（留空則不發送通知）
  # 當檢測到密集村民時，會自動發送警告到 Discord
  # 獲取方法：Discord 伺服器設定 -> 整合 -> Webhook -> 新建 Webhook -> 複製 URL
  webhook-url: ""

# 訊息設定
messages:
  prefix: "&6[DontLag]&r "
  ai-disabled: "&a已關閉 {entity} 的 AI"
  ai-enabled: "&e已恢復 {entity} 的 AI"
  no-permission: "&c你沒有權限使用此功能！"
  tool-enabled: "&a已啟用 AI 控制工具模式！"
  tool-disabled: "&e已關閉 AI 控制工具模式"


